# Generated by Django 4.1 on 2022-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%d/%m/%Y/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
